server.port=8080
spring.application.name=hexamind-hub

# Google API Key
# Google API Key
google.api.key=${GOOGLE_API_KEY}
google.search.cx=${GOOGLE_SEARCH_CX}

# Logging
logging.level.io.github.llm4j=INFO
logging.level.org.springframework.web=INFO
