-- GetViral hosted schema. Portable across PostgreSQL (production) and H2 in PostgreSQL mode (dev/tests).

CREATE TABLE users (
    id              VARCHAR(36)  PRIMARY KEY,
    email           VARCHAR(320) NOT NULL UNIQUE,
    name            VARCHAR(200),
    avatar_url      VARCHAR(1000),
    auth_provider   VARCHAR(40)  NOT NULL,
    handle          VARCHAR(60),
    niche           VARCHAR(80),
    tone            VARCHAR(80),
    audience        VARCHAR(300),
    region          VARCHAR(2),
    onboarding_step VARCHAR(20)  NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE runs (
    id          VARCHAR(36) PRIMARY KEY,
    user_id     VARCHAR(36) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    idea        VARCHAR(600) NOT NULL,
    brief_json  TEXT        NOT NULL,
    status      VARCHAR(20) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at  TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    last_event_at TIMESTAMP WITH TIME ZONE,
    pack_json   TEXT,
    error       TEXT
);
CREATE INDEX runs_user_created ON runs (user_id, created_at);
CREATE INDEX runs_status ON runs (status);

-- The live event log of each run: any instance can stream it to the browser.
CREATE TABLE run_events (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id    VARCHAR(36) NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    seq       INT         NOT NULL,
    type      VARCHAR(40) NOT NULL,
    data_json TEXT        NOT NULL,
    t_ms      BIGINT      NOT NULL,
    CONSTRAINT run_events_seq UNIQUE (run_id, seq)
);

-- Questions the workflow is waiting on (hook pick, publish, approvals). Answers can arrive at any instance.
CREATE TABLE run_questions (
    id           VARCHAR(80) PRIMARY KEY,
    run_id       VARCHAR(36) NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    kind         VARCHAR(20) NOT NULL,
    message      TEXT,
    options_json TEXT,
    answer       TEXT,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    answered_at  TIMESTAMP WITH TIME ZONE
);
CREATE INDEX run_questions_run ON run_questions (run_id);

CREATE TABLE social_connections (
    id                VARCHAR(36) PRIMARY KEY,
    user_id           VARCHAR(36) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    platform          VARCHAR(20) NOT NULL,
    external_id       VARCHAR(200),
    username          VARCHAR(200),
    display_name      VARCHAR(300),
    avatar_url        VARCHAR(1000),
    access_token_enc  TEXT,
    refresh_token_enc TEXT,
    expires_at        TIMESTAMP WITH TIME ZONE,
    scopes            TEXT,
    connected_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT social_connections_user_platform UNIQUE (user_id, platform)
);

CREATE TABLE voice_samples (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(36) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    text       TEXT        NOT NULL,
    source     VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX voice_samples_user ON voice_samples (user_id);

-- Engram memory per creator (synced to the engine's working copy around each run).
CREATE TABLE creator_memory (
    user_id     VARCHAR(36) PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    memory_json TEXT NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Spring Session (JDBC): sessions shared by every instance.
CREATE TABLE SPRING_SESSION (
    PRIMARY_ID            CHAR(36) NOT NULL,
    SESSION_ID            CHAR(36) NOT NULL,
    CREATION_TIME         BIGINT   NOT NULL,
    LAST_ACCESS_TIME      BIGINT   NOT NULL,
    MAX_INACTIVE_INTERVAL INT      NOT NULL,
    EXPIRY_TIME           BIGINT   NOT NULL,
    PRINCIPAL_NAME        VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36)     NOT NULL,
    ATTRIBUTE_NAME     VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES    BYTEA        NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);
