/*
 * Loom graph renderer: lays out and draws a workflow graph as SVG.
 *
 * One plain-JavaScript file with no imports and no network access, so it can be loaded by the VS Code webview and
 * inlined into the single-file eval4j report. The canonical copy is loom/graph-render/graph-render.js; copies are
 * generated by scripts/sync-graph-render.sh and checked by scripts/check-graph-render-sync.sh.
 *
 * Input graph (the JSON of `weave graph`, or the graph of an eval4j workflow trace):
 *   { nodes: [{id, kind, label, agent?, bound?, attrs?, call?, unresolved?, parent?, branch?, source?}],
 *     edges: [{from, to, label?}] }
 * Placement (`parent`, `branch`) may also be in attrs, as the report carries it.
 *
 * Colours come from CSS custom properties (--lg-*) set by the host; fallbacks are built in. Text is always escaped.
 */
(function (root, factory) {
  var api = factory();
  if (typeof module === 'object' && module.exports) { module.exports = api; }
  root.LoomGraph = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  /* ------------------------------------------------------------------ kinds */

  var KIND = {
    start: { k: 'misc', g: null, shape: 'pill' },
    end: { k: 'misc', g: null, shape: 'pill' },
    delegate: { k: 'agent', g: 'agent', shape: 'rect' },
    handoff: { k: 'agent', g: 'handoff', shape: 'rect' },
    broadcast: { k: 'agent', g: 'broadcast', shape: 'rect' },
    task: { k: 'task', g: 'code', shape: 'rect' },
    parallel: { k: 'par', g: 'par', shape: 'bar' },
    alt: { k: 'alt', g: 'alt', shape: 'hex' },
    loop: { k: 'loop', g: 'loop', shape: 'round' },
    foreach: { k: 'loop', g: 'each', shape: 'round' },
    human_prompt: { k: 'human', g: 'person', shape: 'rect' },
    checkpoint: { k: 'misc', g: 'flag', shape: 'flag' },
    rewind: { k: 'misc', g: 'rewind', shape: 'rect' },
    call: { k: 'call', g: 'call', shape: 'dbl' },
    guardrail: { k: 'task', g: 'shield', shape: 'rect' },
    decide: { k: 'call', g: 'scale', shape: 'rect' },
    observe: { k: 'misc', g: 'eye', shape: 'rect' },
    note: { k: 'misc', g: 'note', shape: 'rect', dashed: true },
    unknown: { k: 'misc', g: 'unknown', shape: 'rect', dashed: true },
    statement: { k: 'misc', g: 'unknown', shape: 'rect', dashed: true }
  };
  var CONTAINERS = { alt: 1, loop: 1, foreach: 1, guardrail: 1 };
  var HANDLER_BRANCHES = { failure: 1, exhausted: 1, violation: 1, 'still fails': 1, blocked: 1 };

  var GLYPHS = {
    agent: '<rect x="3" y="4.5" width="10" height="8" rx="2"/><circle class="fill" cx="6.2" cy="8.5" r=".9"/><circle class="fill" cx="9.8" cy="8.5" r=".9"/><path d="M8 4.5V2.2"/>',
    code: '<path d="M5.5 5L2.5 8l3 3M10.5 5l3 3-3 3"/>',
    handoff: '<path d="M2.5 8h8M7.8 4.8L11 8l-3.2 3.2M13.5 3v10"/>',
    broadcast: '<circle class="fill" cx="3.8" cy="8" r="1.4"/><path d="M6.6 5.6l6.6-2.6M6.6 8h6.8M6.6 10.4l6.6 2.6"/>',
    par: '<path d="M5.5 2.5v11M10.5 2.5v11"/>',
    alt: '<path d="M8 2v3.2M8 5.2L3.8 9v4.5M8 5.2L12.2 9v4.5"/>',
    loop: '<path d="M13 8a5 5 0 1 1-1.7-3.8M13 2.5v3.2h-3.2"/>',
    each: '<path d="M3 4h10M3 8h10M3 12h6"/>',
    call: '<path d="M5 11l6-6M6 5h5v5"/>',
    flag: '<path d="M4 2v12M4 3h8l-2 2.6L12 8.2H4"/>',
    rewind: '<path d="M8 4L3 8l5 4zM13 4L8 8l5 4z"/>',
    shield: '<path d="M8 2l5 2v4c0 3-2 5-5 6-3-1-5-3-5-6V4z"/>',
    scale: '<path d="M8 2.5v11M4 13.5h8M3 5.5h10M3 5.5L1.8 9h2.4zM13 5.5L11.8 9h2.4z"/>',
    eye: '<path d="M1.5 8S4 3.8 8 3.8 14.5 8 14.5 8 12 12.2 8 12.2 1.5 8 1.5 8z"/><circle cx="8" cy="8" r="1.9"/>',
    note: '<path d="M3 3h10v10H3zM5.5 6h5M5.5 8.5h5M5.5 11h3"/>',
    person: '<circle cx="8" cy="5.2" r="2.4"/><path d="M3.2 13.5c0-3 2-4.6 4.8-4.6s4.8 1.6 4.8 4.6"/>',
    q: '<path d="M6 6a2 2 0 114 0c0 1.6-2 1.6-2 3.2M8 12v.3"/>',
    hand: '<path d="M5 8.5V4.2a1 1 0 012 0V7V3.4a1 1 0 012 0V7V4a1 1 0 012 0v5.5c0 2.4-1.8 4-4 4S4 12 4 10l-1-2a1 1 0 012 .3z"/>',
    unknown: '<circle cx="8" cy="8" r="5"/><path d="M8 5.5v3M8 10.6v.2"/>'
  };

  var LEGEND = [
    ['agent', 'Agent step (delegate, handoff, broadcast)'], ['task', 'Task or guardrail'], ['par', 'Parallel round'],
    ['alt', 'Branch (alt)'], ['loop', 'Loop or for each'], ['call', 'Call or decision'], ['human', 'Ask a person'],
    ['misc', 'Checkpoint, note, other']
  ];

  /* ---------------------------------------------------------------- helpers */

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }
  function cut(s, n) { s = String(s == null ? '' : s).replace(/\s+/g, ' '); return s.length > n ? s.slice(0, n - 1) + '…' : s; }
  function attrsOf(node) { return node.attrs || {}; }
  function parentOf(node) { return node.parent != null ? node.parent : attrsOf(node).parent; }
  function branchOf(node) { return node.branch != null ? node.branch : attrsOf(node).branch; }
  function kindInfo(node) { return KIND[node.kind] || KIND.unknown; }

  function duration(ms) {
    if (ms % 3600000 === 0) { return ms / 3600000 + 'h'; }
    if (ms % 60000 === 0) { return ms / 60000 + 'm'; }
    if (ms % 1000 === 0) { return ms / 1000 + 's'; }
    if (ms >= 1000) { return +(ms / 1000).toFixed(1) + 's'; }
    return ms + 'ms';
  }
  function count(n) {
    if (n >= 1000000) { return +(n / 1000000).toFixed(1) + 'M'; }
    if (n >= 1000) { return +(n / 1000).toFixed(1) + 'k'; }
    return String(n);
  }
  function plural(n, word) { return n + ' ' + word + (n === 1 ? '' : 's'); }

  /* ------------------------------------------------------------------ chips */

  /** The chips each kind can show, in the order they are drawn. */
  var CHIP_KINDS = {
    delegate: ['timeout', 'retry', 'budget', 'expecting', 'variable'],
    task: ['timeout', 'retry', 'variable'],
    broadcast: ['budget', 'variable'],
    parallel: ['branches'],
    loop: ['max', 'budget'],
    foreach: ['parallel', 'budget'],
    human_prompt: ['variable'],
    checkpoint: ['values'],
    rewind: ['atMost', 'effects', 'carrying'],
    call: ['args', 'variable'],
    decide: ['level']
  };

  function budgetText(b) {
    var parts = [];
    if (b.tokens != null) { parts.push(count(b.tokens) + ' tok'); }
    if (b.calls != null) { parts.push(count(b.calls) + ' calls'); }
    if (b.cost != null) { parts.push('$' + b.cost); }
    if (b.perCall != null) { parts.push(count(b.perCall) + '/call'); }
    if (!parts.length) { return null; }
    return 'budget ' + parts[0] + (parts.length > 1 ? ' +' : '');
  }

  function chipFor(key, node) {
    var a = attrsOf(node);
    switch (key) {
      case 'timeout': return a.timeoutMs ? { t: 'timeout ' + duration(a.timeoutMs) } : null;
      case 'retry': return a.retry ? { t: 'retry ' + a.retry + (a.backoffMs ? ' · ' + duration(a.backoffMs) : '') } : null;
      case 'budget': { var t = a.budget && budgetText(a.budget); return t ? { t: t, v: 'budget' } : null; }
      case 'expecting': return a.expecting ? { t: 'expects ' + cut(a.expecting, 24) } : null;
      case 'max': return node.bound ? { t: 'max ' + node.bound } : (node.kind === 'loop' ? { t: 'no max', v: 'warn' } : null);
      case 'parallel': return a.parallel ? { t: '∥ parallel' } : null;
      case 'branches': return a.branches ? { t: plural(a.branches, 'branch').replace('branchs', 'branches') } : null;
      case 'atMost': return a.atMost ? { t: '≤ ' + a.atMost + (a.atMost === 1 ? ' time' : ' times') } : null;
      case 'effects': return a.effects ? { t: a.effects, v: a.effects === 'ask first' ? 'muted' : undefined } : null;
      case 'carrying': { var n = a.carrying ? Object.keys(a.carrying).length : 0; return n ? { t: 'carrying ' + n } : null; }
      case 'values': { var m = a.startingWith ? Object.keys(a.startingWith).length : 0; return m ? { t: plural(m, 'value') } : null; }
      case 'args': return a.args ? { t: plural(a.args, 'arg') } : null;
      case 'level': return a.level ? { t: String(a.level).toUpperCase() } : null;
      case 'variable': return a.variable ? { t: '→ ' + cut(a.variable, 20) } : null;
      default: return null;
    }
  }

  /** The attribute chips of a node, in the order of its kind's list. All of them; the drawing shows three and "+n". */
  function chips(node) {
    var out = [];
    (CHIP_KINDS[node.kind] || []).forEach(function (key) { var c = chipFor(key, node); if (c) { out.push(c); } });
    return out;
  }

  /* --------------------------------------------------------- title/subtitle */

  function fileName(path) { var p = String(path || '').split(/[\\/]/); return p[p.length - 1]; }

  function subtitle(node, ctx) {
    ctx = ctx || {};
    var a = attrsOf(node), agents = ctx.agents || {};
    switch (node.kind) {
      case 'delegate':
      case 'handoff': {
        if (!node.agent) { return null; }
        var info = agents[node.agent];
        return node.agent + (info && info.model ? ' · ' + info.model : '');
      }
      case 'broadcast':
      case 'parallel': {
        var list = a.agents || [], limit = node.kind === 'broadcast' ? 3 : 4;
        if (!list.length) { return null; }
        return list.slice(0, limit).join(', ') + (list.length > limit ? ' +' + (list.length - limit) : '');
      }
      case 'human_prompt':
      case 'note': return a.text ? cut(a.text, 40) : null;
      case 'observe': return a.text ? cut(a.text, 40) : null;
      case 'rewind': return a.condition ? cut(a.condition, 40) : null;
      case 'task': return a.args ? plural(a.args, 'arg') : null;
      case 'call':
        if (node.unresolved) { return 'not found'; }
        return node.call && node.call.file && node.call.file !== ctx.currentFile ? fileName(node.call.file) : null;
      default: return null;
    }
  }

  function title(node) { return cut(node.label || node.id, 60); }

  /* ----------------------------------------------------------------- sizing */

  function prepared(node, ctx) {
    var info = kindInfo(node), pill = info.shape === 'pill';
    var all = pill ? [] : chips(node), shown = all.slice(0, 3);
    if (all.length > 3) { shown.push({ t: '+' + (all.length - 3) }); }
    var sub = pill ? null : subtitle(node, ctx);
    var h = pill ? 30 : Math.max(44, 14 + 18 + (sub ? 16 : 0) + (shown.length ? 26 : 0) + 6);
    var chipsW = 0; shown.forEach(function (c) { chipsW += Math.ceil(c.t.length * 6) + 12 + 5; });
    var base = pill ? 92 : (info.shape === 'hex' ? 260 : 250);
    var need = pill ? 0 : 36 + chipsW + 12 + (info.shape === 'hex' ? 12 : 0);
    return { node: node, id: node.id, info: info, w: Math.max(base, need), h: h, chips: shown, sub: sub, hidden: 0 };
  }

  /* --------------------------------------------------------------- collapse */

  /** For every node, the top-most collapsed container it is inside of, or itself when none is. */
  function representatives(graph, collapsed) {
    var byId = {}, out = {};
    graph.nodes.forEach(function (n) { byId[n.id] = n; });
    graph.nodes.forEach(function (n) {
      var rep = n.id, p = parentOf(n);
      while (p && byId[p]) { if (collapsed.has(p)) { rep = p; } p = parentOf(byId[p]); }
      out[n.id] = rep;
    });
    return out;
  }

  /** Counts of the nodes inside each container, at any depth. */
  function descendantCounts(graph) {
    var byId = {}, counts = {};
    graph.nodes.forEach(function (n) { byId[n.id] = n; });
    graph.nodes.forEach(function (n) {
      var p = parentOf(n);
      while (p && byId[p]) { counts[p] = (counts[p] || 0) + 1; p = parentOf(byId[p]); }
    });
    return counts;
  }

  /** Containers to collapse so that no more than `limit` nodes are drawn, biggest first. */
  function defaultCollapsed(graph, limit) {
    limit = limit || 300;
    var set = new Set();
    if (graph.nodes.length <= limit) { return set; }
    var counts = descendantCounts(graph), visible = graph.nodes.length;
    var candidates = graph.nodes.filter(function (n) { return CONTAINERS[n.kind] && counts[n.id]; })
      .sort(function (a, b) { return counts[b.id] - counts[a.id]; });
    var byId = {}; graph.nodes.forEach(function (n) { byId[n.id] = n; });
    for (var i = 0; i < candidates.length && visible > limit; i++) {
      var c = candidates[i], p = parentOf(c), inside = false;
      while (p && byId[p]) { if (set.has(p)) { inside = true; break; } p = parentOf(byId[p]); }
      if (inside) { continue; }
      set.add(c.id); visible -= counts[c.id];
    }
    return set;
  }

  /** The graph with collapsed blocks folded into their container node. */
  function visibleGraph(graph, collapsed) {
    collapsed = collapsed || new Set();
    if (!collapsed.size) { return { nodes: graph.nodes, edges: graph.edges, hiddenCount: {} }; }
    var rep = representatives(graph, collapsed), counts = descendantCounts(graph);
    var nodes = graph.nodes.filter(function (n) { return rep[n.id] === n.id; });
    var seen = {}, edges = [];
    graph.edges.forEach(function (e) {
      var a = rep[e.from], b = rep[e.to];
      if (a === b) { return; }
      var key = a + '\u0000' + b + '\u0000' + (e.label || '');
      if (!seen[key]) { seen[key] = 1; edges.push({ from: a, to: b, label: e.label }); }
    });
    var hidden = {}; collapsed.forEach(function (id) { hidden[id] = counts[id] || 0; });
    return { nodes: nodes, edges: edges, hiddenCount: hidden };
  }

  /* ----------------------------------------------------------------- layout */

  var H_GAP = 36, V_GAP = 44, EMPTY_LAYER_GAP = 24, MARGIN = 28, SIDE_ROUTE = 34, SIDE_STEP = 16;

  function isBackLabel(label) { return label === 'again' || label === 'rewind'; }

  /** Splits edges into forward edges (a DAG) and back edges: labelled loops first, then any other cycle found. */
  function splitEdges(ids, edges) {
    var out = {}, inn = {}, back = [], forward = [];
    ids.forEach(function (id) { out[id] = []; inn[id] = []; });
    edges.forEach(function (e) { if (isBackLabel(e.label)) { back.push(e); } else { forward.push(e); out[e.from].push(e); inn[e.to].push(e); } });
    var state = {};
    function visit(id) {
      state[id] = 1;
      out[id].slice().forEach(function (e) {
        if (state[e.to] === 1) { back.push(e); out[id].splice(out[id].indexOf(e), 1); inn[e.to].splice(inn[e.to].indexOf(e), 1); forward.splice(forward.indexOf(e), 1); }
        else if (!state[e.to]) { visit(e.to); }
      });
      state[id] = 2;
    }
    ids.filter(function (id) { return !inn[id].length; }).concat(ids).forEach(function (id) { if (!state[id]) { visit(id); } });
    return { forward: forward, back: back, out: out, inn: inn };
  }

  /**
   * Longest-path layers over the forward edges; `end` goes in the last layer. The step after a loop (the `done` edge)
   * is also kept below the end of the loop body, so the way back up does not run through it.
   */
  function assignLayers(ids, split) {
    var extra = [];
    split.forward.filter(function (e) { return e.label === 'done'; }).forEach(function (exit) {
      split.back.filter(function (b) { return b.label === 'again' && b.to === exit.from; }).forEach(function (b) { extra.push([b.from, exit.to]); });
    });
    var layer = longestPath(ids, split, extra);
    if (!layer) { layer = longestPath(ids, split, []); }
    var deepest = 0;
    ids.forEach(function (id) { deepest = Math.max(deepest, layer[id]); });
    if (layer.end !== undefined && !split.out.end.length) { layer.end = Math.max(layer.end, deepest); }
    return layer;
  }

  /** Longest path layering; null when `extra` edges would make a cycle. */
  function longestPath(ids, split, extra) {
    var layer = {}, indeg = {}, succ = {}, queue = [], done = 0;
    ids.forEach(function (id) { layer[id] = 0; indeg[id] = split.inn[id].length; succ[id] = split.out[id].map(function (e) { return e.to; }); });
    extra.forEach(function (p) { succ[p[0]].push(p[1]); indeg[p[1]]++; });
    ids.forEach(function (id) { if (!indeg[id]) { queue.push(id); } });
    while (queue.length) {
      var u = queue.shift(); done++;
      succ[u].forEach(function (to) { layer[to] = Math.max(layer[to], layer[u] + 1); if (--indeg[to] === 0) { queue.push(to); } });
    }
    return done === ids.length ? layer : null;
  }

  /** An edge that skips layers becomes a chain through one invisible node per skipped layer, so it can be routed past the nodes between. */
  function chainEdges(forward, layer, items, back) {
    var chains = [];
    forward.forEach(function (e) {
      var span = layer[e.to] - layer[e.from];
      if (span < 1) { back.push(e); return; }
      var ids = [e.from];
      for (var k = 1; k < span; k++) {
        var id = '~' + chains.length + ':' + k;
        items[id] = { id: id, dummy: true, w: 10, h: 0 }; layer[id] = layer[e.from] + k; ids.push(id);
      }
      ids.push(e.to); chains.push({ edge: e, ids: ids });
    });
    return chains;
  }

  /** Orders each layer: first by a depth-first walk in the order the edges are written (then before else), then by barycentre sweeps. */
  function orderLayers(items, layer, chains) {
    var up = {}, down = {}, layers = [], rank = {}, counter = 0, seen = {};
    Object.keys(items).forEach(function (id) { up[id] = []; down[id] = []; (layers[layer[id]] = layers[layer[id]] || []).push(id); });
    layers = Array.from(layers, function (l) { return l || []; });
    chains.forEach(function (c) { for (var i = 0; i + 1 < c.ids.length; i++) { down[c.ids[i]].push(c.ids[i + 1]); up[c.ids[i + 1]].push(c.ids[i]); } });
    function walk(id) { if (seen[id]) { return; } seen[id] = 1; rank[id] = counter++; down[id].forEach(walk); }
    layers.forEach(function (l) { l.forEach(function (id) { if (!up[id].length) { walk(id); } }); });
    Object.keys(items).forEach(walk);
    layers.forEach(function (l) { l.sort(function (a, b) { return rank[a] - rank[b]; }); });
    function positions() { var pos = {}; layers.forEach(function (l) { l.forEach(function (id, i) { pos[id] = i; }); }); return pos; }
    function centre(id, nb, pos) { var ns = nb[id]; if (!ns.length) { return pos[id]; } return ns.reduce(function (s, n) { return s + pos[n]; }, 0) / ns.length; }
    function sweep(from, to, step, nb) {
      for (var i = from; step > 0 ? i < to : i > to; i += step) {
        var pos = positions();
        layers[i].sort(function (a, b) { return (centre(a, nb, pos) - centre(b, nb, pos)) || (pos[a] - pos[b]); });
      }
    }
    for (var round = 0; round < 4; round++) { sweep(1, layers.length, 1, up); sweep(layers.length - 2, -1, -1, down); }
    return { layers: layers, up: up, down: down };
  }

  /** Horizontal positions: spread each layer, then pull nodes toward their neighbours without letting them overlap. */
  function assignX(items, order) {
    var x = {}, layers = order.layers;
    layers.forEach(function (l) {
      var total = l.reduce(function (s, id) { return s + items[id].w; }, 0) + H_GAP * Math.max(0, l.length - 1), cx = -total / 2;
      l.forEach(function (id) { x[id] = cx + items[id].w / 2; cx += items[id].w + H_GAP; });
    });
    function separate(l) {
      for (var i = 1; i < l.length; i++) { var min = x[l[i - 1]] + items[l[i - 1]].w / 2 + H_GAP + items[l[i]].w / 2; if (x[l[i]] < min) { x[l[i]] = min; } }
    }
    function pull(nb, from, to, step) {
      for (var i = from; step > 0 ? i < to : i > to; i += step) {
        layers[i].forEach(function (id) { var ns = nb[id]; if (ns.length) { x[id] = ns.reduce(function (s, n) { return s + x[n]; }, 0) / ns.length; } });
        separate(layers[i]);
      }
    }
    for (var iter = 0; iter < 6; iter++) { pull(order.up, 1, layers.length, 1); pull(order.down, layers.length - 2, -1, -1); }
    return x;
  }

  /** Vertical positions: layers stack with a gap; nodes in a layer are centred on the layer's tallest. */
  function assignY(items, layers) {
    var y = {}, top = 0;
    layers.forEach(function (l) {
      var height = l.reduce(function (m, id) { return Math.max(m, items[id].h); }, 0);
      l.forEach(function (id) { y[id] = top + (height - items[id].h) / 2; });
      top += height ? height + V_GAP : EMPTY_LAYER_GAP;
    });
    return y;
  }

  /** Orthogonal path for an edge through its chain: down from the source, across, down again at each layer. */
  function routeChain(chain, geometry) {
    var ids = chain.ids, pts = [[geometry.cx(ids[0]), geometry.bottom(ids[0])]], labelAt = null;
    for (var i = 1; i < ids.length; i++) {
      var prev = ids[i - 1], cur = ids[i], px = geometry.cx(prev), nx = geometry.cx(cur);
      var gap = geometry.top(cur) - geometry.bottom(prev);
      // a long edge turns just below its source so the run across does not cut through the layers it skips
      var ym = geometry.bottom(prev) + (i === 1 && ids.length > 2 ? Math.min(14, gap / 2) : gap / 2);
      pts.push([px, ym], [nx, ym], [nx, geometry.top(cur)]);
      if (labelAt === null) { labelAt = Math.abs(px - nx) > 1 ? [(px + nx) / 2, ym] : [px, geometry.bottom(prev) + gap / 2]; }
      if (i < ids.length - 1) { pts.push([nx, geometry.bottom(cur)]); }
    }
    return { from: ids[0], to: ids[ids.length - 1], label: chain.edge.label, pts: pts, lx: labelAt[0], ly: labelAt[1], back: false };
  }

  /** True when another node sits to that side of `node` in its own layer, so a line leaving that side would cross it. */
  function blocked(placed, node, side) {
    return Object.keys(placed).some(function (id) {
      var o = placed[id];
      return o !== node && o.layer === node.layer && (side === 'right' ? o.x > node.x : o.x < node.x);
    });
  }

  /**
   * Loop and rewind edges leave a side of their source, run down beside the drawing and enter the same side of the
   * target. The right side is used unless a node is in the way there and the left is clear.
   */
  function routeBack(edges, placed) {
    var routes = [], lanes = { right: 0, left: 0 };
    edges.forEach(function (e) {
      var a = placed[e.from], b = placed[e.to]; if (!a || !b) { return; }
      var side = blocked(placed, a, 'right') || blocked(placed, b, 'right') ? (blocked(placed, a, 'left') || blocked(placed, b, 'left') ? 'right' : 'left') : 'right';
      var lo = Math.min(a.layer, b.layer), hi = Math.max(a.layer, b.layer), edge = side === 'right' ? -Infinity : Infinity;
      Object.keys(placed).forEach(function (id) {
        var n = placed[id]; if (n.layer < lo || n.layer > hi) { return; }
        edge = side === 'right' ? Math.max(edge, n.x + n.w) : Math.min(edge, n.x);
      });
      var offset = SIDE_ROUTE + lanes[side]++ * SIDE_STEP, lane = side === 'right' ? edge + offset : edge - offset;
      var ay = a.y + a.h / 2, by = b.y + b.h / 2, ax = side === 'right' ? a.x + a.w : a.x, bx = side === 'right' ? b.x + b.w : b.x;
      routes.push({ from: a.id, to: b.id, label: e.label, pts: [[ax, ay], [lane, ay], [lane, by], [bx, by]], lx: lane, ly: (ay + by) / 2, back: true });
    });
    return routes;
  }

  /**
   * Layered layout, top to bottom. Returns {nodes: [{id, node, x, y, w, h, chips, sub, ...}], routes: [{pts, label, ...}],
   * bounds}. `collapsed` is a Set of container ids drawn as a single node.
   */
  function layout(graph, ctx, collapsed) {
    var vg = visibleGraph(graph, collapsed), items = {}, ids = [];
    if (!vg.nodes.length) { return { nodes: [], routes: [], bounds: { x: -MARGIN, y: -MARGIN, w: 2 * MARGIN, h: 2 * MARGIN }, hiddenCount: {} }; }
    vg.nodes.forEach(function (n) {
      var p = prepared(n, ctx), hidden = vg.hiddenCount[n.id];
      if (hidden) { p.hidden = hidden; p.chips = p.chips.slice(0, 2).concat([{ t: '+' + hidden + ' steps', v: 'toggle' }]); p.w = Math.max(p.w, 188); p.h = Math.max(p.h, 14 + 18 + (p.sub ? 16 : 0) + 26 + 6); }
      items[n.id] = p; ids.push(n.id);
    });
    var edges = vg.edges.filter(function (e) { return items[e.from] && items[e.to] && e.from !== e.to; });
    var split = splitEdges(ids, edges), layer = assignLayers(ids, split), back = split.back.slice();
    var chains = chainEdges(split.forward, layer, items, back);
    var order = orderLayers(items, layer, chains), x = assignX(items, order), y = assignY(items, order.layers);

    var minX = Infinity, maxX = -Infinity;
    ids.forEach(function (id) { minX = Math.min(minX, x[id] - items[id].w / 2); maxX = Math.max(maxX, x[id] + items[id].w / 2); });
    if (!isFinite(minX)) { minX = 0; maxX = 0; }
    var placed = {}, nodes = [];
    ids.forEach(function (id) {
      var it = items[id], p = { id: id, node: it.node, info: it.info, w: it.w, h: it.h, chips: it.chips, sub: it.sub, hidden: it.hidden, x: x[id] - it.w / 2 - minX, y: y[id], layer: layer[id] };
      placed[id] = p; nodes.push(p);
    });
    var geometry = {
      cx: function (id) { return placed[id] ? placed[id].x + placed[id].w / 2 : x[id] - minX; },
      top: function (id) { return placed[id] ? placed[id].y : y[id]; },
      bottom: function (id) { return placed[id] ? placed[id].y + placed[id].h : y[id]; }
    };
    var routes = chains.map(function (c) { return routeChain(c, geometry); }).concat(routeBack(back, placed));
    return { nodes: nodes, routes: routes, bounds: bounds(nodes, routes, maxX - minX), hiddenCount: vg.hiddenCount };
  }

  function bounds(nodes, routes, width) {
    var x0 = 0, x1 = width, y1 = 0;
    nodes.forEach(function (n) { y1 = Math.max(y1, n.y + n.h); });
    routes.forEach(function (r) { r.pts.forEach(function (p) { x0 = Math.min(x0, p[0]); x1 = Math.max(x1, p[0] + (r.back ? 40 : 0)); }); });
    return { x: x0 - MARGIN, y: -MARGIN, w: x1 - x0 + 2 * MARGIN, h: y1 + 2 * MARGIN };
  }

  /* ---------------------------------------------------------------- overlay */

  /** What happened in one run: the state of each node, how often it was visited, and which edges were taken. */
  function overlay(graph, expectedPath, actualPath) {
    expectedPath = expectedPath || []; actualPath = actualPath || [];
    var exp = {}, act = {}, visits = {}, states = {};
    expectedPath.forEach(function (id) { exp[id] = 1; });
    actualPath.forEach(function (id) { act[id] = 1; visits[id] = (visits[id] || 0) + 1; });
    var hasExpected = expectedPath.length > 0;
    graph.nodes.forEach(function (n) {
      var inExp = !!exp[n.id], inAct = !!act[n.id];
      states[n.id] = inAct ? (hasExpected ? (inExp ? 'ok' : 'unexpected') : 'taken') : (inExp ? 'missed' : 'none');
    });
    var edgeSet = {}; graph.edges.forEach(function (e) { edgeSet[e.from + '\u0000' + e.to] = 1; });
    var traversed = [], seen = {};
    for (var i = 0; i + 1 < actualPath.length; i++) {
      var key = actualPath[i] + '\u0000' + actualPath[i + 1];
      if (edgeSet[key] && !seen[key]) { seen[key] = 1; traversed.push([actualPath[i], actualPath[i + 1]]); }
    }
    return { states: states, visits: visits, traversed: traversed, hasExpected: hasExpected, empty: actualPath.length === 0 };
  }

  var MARK = {
    ok: { glyph: '✓', text: 'taken as expected' }, taken: { glyph: '●', text: 'taken' },
    missed: { glyph: '✗', text: 'missed' }, unexpected: { glyph: '!', text: 'unexpected' }
  };

  /* ---------------------------------------------------------------- drawing */

  var CSS = [
    '.lg-edge{fill:none;stroke:var(--lg-edge,#68708c);stroke-width:1.5;stroke-linejoin:round}',
    '.lg-edge.lg-dash{stroke-dasharray:5 4}',
    '.lg-edge.lg-trav{stroke:var(--lg-ink,var(--lg-fg,#1d2130));stroke-width:2.6}',
    '.lg-edge.lg-untrav{opacity:.45}',
    '.lg-elabel rect{fill:var(--lg-surface,#fff);stroke:var(--lg-line,#d6d9e5)}',
    '.lg-elabel text{fill:var(--lg-muted,#5a6177);font:10.5px var(--lg-mono,ui-monospace,Menlo,monospace);text-anchor:middle}',
    '.lg-arrow{fill:var(--lg-edge,#68708c)}',
    '.lg-node{cursor:pointer;outline:none}',
    '.lg-node.lg-agent{--k:var(--lg-blue,#2765cf)}.lg-node.lg-task{--k:var(--lg-teal,#0b827a)}.lg-node.lg-par{--k:var(--lg-green,#2a7f38)}',
    '.lg-node.lg-alt{--k:var(--lg-amber,#955f00)}.lg-node.lg-loop{--k:var(--lg-violet,#7140d0)}.lg-node.lg-call{--k:var(--lg-magenta,#b02c82)}',
    '.lg-node.lg-human{--k:var(--lg-orange,#c4501a)}.lg-node.lg-misc{--k:var(--lg-grey,#5f6678)}.lg-node.lg-bad{--k:var(--lg-red,#c93232)}',
    '.lg-shape{fill:color-mix(in srgb,var(--k) 12%,var(--lg-surface,#fff));stroke:var(--k);stroke-width:1.5}',
    '.lg-dashed .lg-shape{stroke-dasharray:5 3}',
    '.lg-node.lg-sel .lg-shape,.lg-node:focus-visible .lg-shape{stroke:var(--lg-sel,#5a54e0);stroke-width:3}',
    '.lg-bar{fill:var(--k)}.lg-dbl{stroke:var(--k);stroke-width:1.2;fill:none}',
    '.lg-title{fill:var(--lg-fg,#1d2130);font:600 12.5px var(--lg-font,system-ui,sans-serif)}',
    '.lg-sub{fill:var(--lg-muted,#5a6177);font:11px var(--lg-font,system-ui,sans-serif)}',
    '.lg-glyph{stroke:var(--k);fill:none;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}.lg-glyph .fill{fill:var(--k)}',
    '.lg-chipbox{fill:var(--lg-chip-bg,#eceff7);stroke:var(--lg-chip-line,#cfd4e3)}',
    '.lg-chiptx{fill:var(--lg-muted,#5a6177);font:10px var(--lg-mono,ui-monospace,Menlo,monospace)}',
    '.lg-chip-budget .lg-chipbox{stroke:var(--lg-amber,#955f00)}.lg-chip-budget .lg-chiptx{fill:var(--lg-amber,#955f00)}',
    '.lg-chip-warn .lg-chipbox{stroke:var(--lg-red,#c93232)}.lg-chip-warn .lg-chiptx{fill:var(--lg-red,#c93232)}',
    '.lg-chip-toggle .lg-chipbox{stroke:var(--lg-sel,#5a54e0)}.lg-chip-toggle .lg-chiptx{fill:var(--lg-sel,#5a54e0)}',
    '.lg-chip-muted .lg-chiptx{opacity:.7}',
    '.lg-chip-toggle{cursor:pointer}',
    '.lg-approve{--k:var(--lg-orange,#c4501a)}',
    '.lg-dim{opacity:.45}',
    '.lg-state-ok .lg-markbox{fill:var(--lg-good,#2a7f38)}.lg-state-taken .lg-markbox{fill:var(--lg-muted,#5a6177)}',
    '.lg-state-missed .lg-markbox,.lg-state-unexpected .lg-markbox{fill:var(--lg-surface,#fff)}',
    '.lg-state-missed .lg-markline{stroke:var(--lg-red,#c93232)}.lg-state-missed .lg-marktx{fill:var(--lg-red,#c93232)}',
    '.lg-state-unexpected .lg-markline{stroke:var(--lg-amber,#955f00)}.lg-state-unexpected .lg-marktx{fill:var(--lg-amber,#955f00)}',
    '.lg-state-ok .lg-marktx,.lg-state-taken .lg-marktx{fill:var(--lg-on-mark,#fff)}',
    '.lg-state-missed .lg-shape{stroke-dasharray:5 3;fill:var(--lg-surface,#fff)}.lg-state-unexpected .lg-shape{stroke:var(--lg-amber,#955f00);stroke-width:2.4}',
    '.lg-markline{fill:none;stroke-width:1.2}.lg-marktx{font:600 10px var(--lg-font,system-ui,sans-serif)}',
    '.lg-toggle{cursor:pointer}.lg-toggle circle{fill:var(--lg-surface,#fff);stroke:var(--lg-sel,#5a54e0)}.lg-toggle text{fill:var(--lg-sel,#5a54e0);font:700 11px var(--lg-font,system-ui,sans-serif);text-anchor:middle}'
  ].join('\n');

  function shapeSvg(p) {
    var x = p.x, y = p.y, w = p.w, h = p.h;
    switch (p.info.shape) {
      case 'pill': return '<rect class="lg-shape" x="' + x + '" y="' + y + '" width="' + w + '" height="' + h + '" rx="' + h / 2 + '"/>';
      case 'hex': return '<polygon class="lg-shape" points="' + [[x + 16, y], [x + w - 16, y], [x + w, y + h / 2], [x + w - 16, y + h], [x + 16, y + h], [x, y + h / 2]].map(function (q) { return q.join(','); }).join(' ') + '"/>';
      case 'round': return '<rect class="lg-shape" x="' + x + '" y="' + y + '" width="' + w + '" height="' + h + '" rx="16"/>';
      case 'bar': return '<rect class="lg-shape" x="' + x + '" y="' + y + '" width="' + w + '" height="' + h + '" rx="6"/><rect class="lg-bar" x="' + (x + 6) + '" y="' + (y + 4) + '" width="' + (w - 12) + '" height="2" rx="1"/><rect class="lg-bar" x="' + (x + 6) + '" y="' + (y + 8) + '" width="' + (w - 12) + '" height="2" rx="1"/>';
      case 'dbl': return '<rect class="lg-shape" x="' + x + '" y="' + y + '" width="' + w + '" height="' + h + '" rx="6"/><path class="lg-dbl" d="M' + (x + 6) + ' ' + (y + 3) + 'V' + (y + h - 3) + 'M' + (x + w - 6) + ' ' + (y + 3) + 'V' + (y + h - 3) + '"/>';
      case 'flag': return '<path class="lg-shape" d="M' + x + ' ' + y + 'H' + (x + w) + 'L' + (x + w - 12) + ' ' + (y + h / 2) + 'L' + (x + w) + ' ' + (y + h) + 'H' + x + 'z"/>';
      default: return '<rect class="lg-shape" x="' + x + '" y="' + y + '" width="' + w + '" height="' + h + '" rx="6"/>';
    }
  }

  function nodeSvg(p, opts) {
    var node = p.node, info = p.info, pill = info.shape === 'pill', hex = info.shape === 'hex';
    var st = opts.overlay && opts.overlay.states[p.id];
    var cls = 'lg-node lg-' + (node.unresolved ? 'bad' : info.k) + (info.dashed || node.unresolved ? ' lg-dashed' : '') +
      (opts.selected === p.id ? ' lg-sel' : '') + (st ? ' lg-state-' + st : '') + (st === 'none' ? ' lg-dim' : '');
    var label = title(node) + (node.source ? ', line ' + node.source.line : '');
    var aria = label + (st && MARK[st] ? ', ' + MARK[st].text : '');
    var out = '<g class="' + cls + '" data-id="' + esc(p.id) + '" role="button" tabindex="0" aria-label="' + esc(aria) + '"><title>' + esc(cut(node.label || node.id, 500)) + '</title>';
    out += shapeSvg(p);
    if (pill) {
      out += '<text class="lg-title" x="' + (p.x + p.w / 2) + '" y="' + (p.y + 19) + '" text-anchor="middle">' + esc(title(node)) + '</text>';
      return out + (st && MARK[st] ? markSvg(p, st, opts.overlay.visits[p.id]) : '') + '</g>';
    }
    var gx = p.x + (hex ? 24 : info.shape === 'dbl' ? 16 : 12), tx = gx + 24;
    var maxc = Math.max(8, Math.floor((p.w - (tx - p.x) - (st ? 56 : 30)) / 6.6));
    out += '<g class="lg-glyph" transform="translate(' + gx + ',' + (p.y + 9) + ')">' + GLYPHS[node.unresolved ? 'q' : (info.g || 'unknown')] + '</g>';
    out += '<text class="lg-title" x="' + tx + '" y="' + (p.y + 22) + '">' + esc(cut(title(node), maxc)) + '</text>';
    if (p.sub) { out += '<text class="lg-sub" x="' + tx + '" y="' + (p.y + 38) + '">' + esc(cut(p.sub, maxc + 4)) + '</text>'; }
    var cx = tx, cy = p.y + p.h - 24, shown = p.chips.slice();
    if (node.unresolved) { shown.unshift({ t: '?', v: 'warn' }); }
    shown.forEach(function (c) {
      var cw = Math.ceil(c.t.length * 6) + 12;
      out += '<g class="lg-chip-' + esc(c.v || 'plain') + '"' + (c.v === 'toggle' ? ' data-toggle="' + esc(p.id) + '"' : '') + '><rect class="lg-chipbox" x="' + cx + '" y="' + cy + '" width="' + cw + '" height="17" rx="4"/><text class="lg-chiptx" x="' + (cx + 6) + '" y="' + (cy + 12.2) + '">' + esc(c.t) + '</text></g>';
      cx += cw + 5;
    });
    var ag = node.agent && opts.agents && opts.agents[node.agent];
    if (ag && (ag.approveAll || (ag.approve && ag.approve.length))) {
      out += '<g class="lg-glyph lg-approve" transform="translate(' + (p.x + p.w - 24) + ',' + (p.y + 8) + ')"><title>Needs approval' + (ag.approve && ag.approve.length ? ': ' + esc(ag.approve.join(', ')) : '') + '</title>' + GLYPHS.hand + '</g>';
    }
    if (st && MARK[st]) { out += markSvg(p, st, opts.overlay.visits[p.id]); }
    else if (opts.overlay && opts.overlay.visits[p.id] > 1) { out += visitsSvg(p, opts.overlay.visits[p.id]); }
    if (opts.showToggles && CONTAINERS[node.kind] && (p.hidden || opts.toggleable && opts.toggleable[p.id])) {
      out += '<g class="lg-toggle" data-toggle="' + esc(p.id) + '"><title>' + (p.hidden ? 'Expand' : 'Collapse') + '</title><circle cx="' + (p.x + p.w - 10) + '" cy="' + (p.y + p.h - 10) + '" r="8"/><text x="' + (p.x + p.w - 10) + '" y="' + (p.y + p.h - 6) + '">' + (p.hidden ? '+' : '−') + '</text></g>';
    }
    return out + '</g>';
  }

  function markSvg(p, st, visits) {
    var m = MARK[st], text = st === 'ok' || st === 'taken' ? m.glyph : m.glyph + ' ' + m.text;
    var w = st === 'ok' || st === 'taken' ? 18 : Math.ceil(text.length * 6.4) + 12, x = p.x + p.w - w - 8, y = p.y - 8;
    var out = '<g><rect class="lg-markbox" x="' + x + '" y="' + y + '" width="' + w + '" height="17" rx="8.5"/><rect class="lg-markline" x="' + x + '" y="' + y + '" width="' + w + '" height="17" rx="8.5"/><text class="lg-marktx" x="' + (x + w / 2) + '" y="' + (y + 12) + '" text-anchor="middle">' + esc(text) + '</text><title>' + esc(m.text) + '</title></g>';
    if (visits > 1) { out += visitsSvg(p, visits, x - 34); }
    return out;
  }
  function visitsSvg(p, n, x) {
    x = x == null ? p.x + p.w - 42 : x;
    return '<g><rect class="lg-chipbox" x="' + x + '" y="' + (p.y - 8) + '" width="30" height="17" rx="8.5"/><text class="lg-chiptx" x="' + (x + 15) + '" y="' + (p.y + 4) + '" text-anchor="middle">×' + n + '</text><title>visited ' + n + ' times</title></g>';
  }

  function path(pts) { return pts.map(function (p, i) { return (i ? 'L' : 'M') + Math.round(p[0] * 10) / 10 + ' ' + Math.round(p[1] * 10) / 10; }).join(' '); }

  /** The SVG markup of a laid-out graph: edges first, then nodes. Pure; the host puts it in an <svg>. */
  function drawing(lay, opts) {
    opts = opts || {};
    var travSet = {}; if (opts.overlay) { opts.overlay.traversed.forEach(function (t) { travSet[t[0] + '\u0000' + t[1]] = 1; }); }
    var out = '';
    lay.routes.forEach(function (r) {
      var cls = 'lg-edge' + (r.label === 'rewind' ? ' lg-dash' : '') + (opts.overlay ? (travSet[r.from + '\u0000' + r.to] ? ' lg-trav' : ' lg-untrav') : '');
      out += '<path class="' + cls + '" d="' + path(r.pts) + '" marker-end="url(#lg-arrow)" data-from="' + esc(r.from) + '" data-to="' + esc(r.to) + '"/>';
      if (r.label) { var w = r.label.length * 6.4 + 12; out += '<g class="lg-elabel"><rect x="' + (r.lx - w / 2) + '" y="' + (r.ly - 9) + '" width="' + w + '" height="18" rx="9"/><text x="' + r.lx + '" y="' + (r.ly + 3.8) + '">' + esc(r.label) + '</text></g>'; }
    });
    lay.nodes.forEach(function (p) { out += nodeSvg(p, opts); });
    return out;
  }

  var DEFS = '<defs><marker id="lg-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerUnits="userSpaceOnUse" markerWidth="9" markerHeight="9" orient="auto-start-reverse"><path class="lg-arrow" d="M0 1L10 5L0 9z"/></marker></defs>';

  /** A complete, self-contained <svg> element as text: styles, marker and drawing. Used for tests and static output. */
  function svgText(graph, opts) {
    opts = opts || {};
    var lay = layout(graph, opts, opts.collapsed), b = lay.bounds;
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="' + [b.x, b.y, b.w, b.h].join(' ') + '" width="' + b.w + '" height="' + b.h + '" role="group" aria-label="Workflow graph"><style>' + CSS + '</style>' + DEFS + drawing(lay, opts) + '</svg>';
  }

  /* ------------------------------------------------------------------- view */

  /**
   * An interactive graph in a container: pan, zoom, fit, selection and keyboard. DOM only.
   * options: onSelect(id, node), onActivate(id, node, {shift, ctrl}), onHover(id, node, element), onToggle(id),
   * onZoom(k), embedCss (default true; false when the host loads graph-render.css itself)
   */
  function View(container, options) {
    this.options = options || {};
    this.container = container;
    var doc = container.ownerDocument;
    this.svg = doc.createElementNS('http://www.w3.org/2000/svg', 'svg');
    this.svg.setAttribute('role', 'group'); this.svg.setAttribute('aria-label', 'Workflow graph');
    this.svg.style.cssText = 'width:100%;height:100%;display:block;touch-action:none;cursor:grab';
    // a host with a strict content-security policy sets embedCss: false and loads the same rules from a file
    this.svg.innerHTML = (this.options.embedCss === false ? '' : '<style>' + CSS + '</style>') + DEFS + '<g class="lg-vp"></g>';
    container.appendChild(this.svg);
    this.vp = this.svg.querySelector('.lg-vp');
    this.t = { k: 1, x: 0, y: 0 };
    this.graph = null; this.ctx = {}; this.collapsed = new Set(); this.selected = null; this.overlayData = null; this.lay = null;
    this._wire();
  }
  View.prototype.setGraph = function (graph, ctx, keep) {
    this.graph = graph; this.ctx = ctx || {};
    this.collapsed = this.ctx.collapsed || defaultCollapsed(graph, this.ctx.collapseLimit || 300);
    this.draw(); if (!keep) { this.fit(); } else { this._apply(); }
  };
  View.prototype.draw = function () {
    if (!this.graph) { return; }
    this.lay = layout(this.graph, this.ctx, this.collapsed);
    var toggleable = {}; var counts = descendantCounts(this.graph); Object.keys(counts).forEach(function (id) { toggleable[id] = true; });
    this.vp.innerHTML = drawing(this.lay, { selected: this.selected, overlay: this.overlayData, agents: this.ctx.agents, showToggles: this.graph.nodes.length > (this.ctx.collapseLimit || 300) || this.collapsed.size > 0, toggleable: toggleable });
    this._apply();
  };
  View.prototype.setOverlay = function (data) { this.overlayData = data; this.draw(); };
  /** Marks a step as selected without redrawing, so a double-click on it still reaches the same element. */
  View.prototype.select = function (id) {
    var before = this.selected && this.nodeElement(this.selected), now = id && this.nodeElement(id);
    this.selected = id;
    if (before) { before.classList.remove('lg-sel'); }
    if (now) { now.classList.add('lg-sel'); }
  };
  View.prototype.toggle = function (id) { if (this.collapsed.has(id)) { this.collapsed.delete(id); } else { this.collapsed.add(id); } this.draw(); this.fitIfNeeded && this.fitIfNeeded(); };
  View.prototype._apply = function () { this.vp.setAttribute('transform', 'translate(' + this.t.x + ',' + this.t.y + ') scale(' + this.t.k + ')'); if (this.options.onZoom) { this.options.onZoom(this.t.k); } };
  View.prototype.fit = function () {
    var r = this.svg.getBoundingClientRect(); if (!this.lay || !r.width || !r.height) { return; }
    var b = this.lay.bounds, k = Math.min(r.width / b.w, r.height / b.h, 1.15);
    this.t = { k: k, x: (r.width - b.w * k) / 2 - b.x * k, y: Math.max(8, (r.height - b.h * k) / 2) - b.y * k }; this._apply();
  };
  View.prototype.zoomBy = function (f, cx, cy) {
    var r = this.svg.getBoundingClientRect(); cx = cx == null ? r.width / 2 : cx; cy = cy == null ? r.height / 2 : cy;
    var t = this.t, k = Math.min(2.5, Math.max(0.2, t.k * f)), q = k / t.k; t.x = cx - (cx - t.x) * q; t.y = cy - (cy - t.y) * q; t.k = k; this._apply();
  };
  View.prototype.nodeElement = function (id) { return this.vp.querySelector('.lg-node[data-id="' + String(id).replace(/"/g, '') + '"]'); };
  View.prototype.revealNode = function (id) {
    var p = this.lay && this.lay.nodes.filter(function (n) { return n.id === id; })[0]; if (!p) { return; }
    var r = this.svg.getBoundingClientRect(), t = this.t, sx = (p.x + p.w / 2) * t.k + t.x, sy = (p.y + p.h / 2) * t.k + t.y;
    if (sx < 20 || sy < 20 || sx > r.width - 20 || sy > r.height - 20) { t.x += r.width / 2 - sx; t.y += r.height / 2 - sy; this._apply(); }
  };
  View.prototype._wire = function () {
    var self = this, svg = this.svg, drag = null, o = this.options;
    function nodeOf(target) { var g = target.closest && target.closest('.lg-node'); return g ? g.getAttribute('data-id') : null; }
    function graphNode(id) { return self.graph && self.graph.nodes.filter(function (n) { return n.id === id; })[0]; }
    svg.addEventListener('pointerdown', function (e) { if (nodeOf(e.target) || (e.target.closest && e.target.closest('[data-toggle]'))) { return; } drag = { x: e.clientX, y: e.clientY, tx: self.t.x, ty: self.t.y, moved: false }; svg.setPointerCapture(e.pointerId); svg.style.cursor = 'grabbing'; });
    svg.addEventListener('pointermove', function (e) { if (!drag) { return; } if (Math.abs(e.clientX - drag.x) + Math.abs(e.clientY - drag.y) > 3) { drag.moved = true; } self.t.x = drag.tx + e.clientX - drag.x; self.t.y = drag.ty + e.clientY - drag.y; self._apply(); });
    function end() { drag = null; svg.style.cursor = 'grab'; }
    svg.addEventListener('pointerup', end); svg.addEventListener('pointercancel', end);
    svg.addEventListener('click', function (e) {
      var tg = e.target.closest && e.target.closest('[data-toggle]');
      if (tg) { e.stopPropagation(); var id0 = tg.getAttribute('data-toggle'); self.toggle(id0); if (o.onToggle) { o.onToggle(id0); } return; }
      var id = nodeOf(e.target);
      if (id) { e.stopPropagation(); if (e.ctrlKey || e.metaKey) { if (o.onActivate) { o.onActivate(id, graphNode(id), { ctrl: true }); } return; } self.select(id); if (o.onSelect) { o.onSelect(id, graphNode(id)); } }
      else if (self.selected && !(drag && drag.moved)) { self.selected = null; self.draw(); if (o.onSelect) { o.onSelect(null, null); } }
    });
    svg.addEventListener('dblclick', function (e) { var id = nodeOf(e.target); if (id && o.onActivate) { o.onActivate(id, graphNode(id), {}); } });
    svg.addEventListener('wheel', function (e) { if (!(e.ctrlKey || e.metaKey)) { return; } e.preventDefault(); var r = svg.getBoundingClientRect(); self.zoomBy(e.deltaY < 0 ? 1.1 : 1 / 1.1, e.clientX - r.left, e.clientY - r.top); }, { passive: false });
    svg.addEventListener('keydown', function (e) {
      var id = nodeOf(e.target); if (!id) { return; }
      if (e.key === 'Enter') { e.preventDefault(); if (e.shiftKey) { if (o.onActivate) { o.onActivate(id, graphNode(id), { shift: true }); } } else { self.select(id); if (o.onSelect) { o.onSelect(id, graphNode(id)); } var el = self.nodeElement(id); if (el) { el.focus(); } } }
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') { e.preventDefault(); var ids = self.lay.nodes.map(function (n) { return n.id; }), i = ids.indexOf(id) + (e.key === 'ArrowDown' ? 1 : -1), el2 = ids[i] && self.nodeElement(ids[i]); if (el2) { el2.focus(); self.revealNode(ids[i]); } }
      if (e.key === 'Escape' && o.onHover) { o.onHover(null, null, null); }
    });
    svg.addEventListener('pointerover', function (e) { var id = nodeOf(e.target); if (id && o.onHover) { o.onHover(id, graphNode(id), self.nodeElement(id)); } });
    svg.addEventListener('pointerout', function (e) { var id = nodeOf(e.target); if (id && o.onHover) { o.onHover(null, null, null); } });
    svg.addEventListener('focusin', function (e) { var id = nodeOf(e.target); if (id && o.onHover) { o.onHover(id, graphNode(id), self.nodeElement(id)); } });
    svg.addEventListener('focusout', function (e) { var id = nodeOf(e.target); if (id && o.onHover) { o.onHover(null, null, null); } });
  };

  return {
    version: 1, css: CSS, kinds: KIND, legend: function () { return LEGEND.slice(); },
    chips: chips, subtitle: subtitle, title: title, duration: duration, budgetText: budgetText,
    layout: layout, drawing: drawing, svgText: svgText, overlay: overlay,
    defaultCollapsed: defaultCollapsed, visibleGraph: visibleGraph, descendantCounts: descendantCounts,
    esc: esc, View: View
  };
});
